"""Domain models and data structures for optimization and self-consumption metrics."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum


class OptimizationStrategy(StrEnum):
    """Distribution coefficient allocation strategies."""

    OPTIMAL = "optimal"
    CONSUMPTION_SHARE = "consumption_share"
    EQUAL = "equal"


@dataclass(frozen=True)
class CupsMonthlyMetrics:
    """Monthly self-consumption and energy metrics for an individual CUPS.

    Attributes:
        cups: Universal Supply Point Code identifier.
        month: Year-month identifier (e.g. '2026-05').
        beta: Assigned allocation coefficient (0.0 to 1.0).
        consumption_kwh: Total energy demanded by this supply point in the month.
        generation_allocated_kwh: Share of solar PV generation allocated (beta * total_gen).
        self_consumed_kwh: Solar energy self-consumed on-site (min(consumption, allocated_gen)).
        surplus_kwh: Excess solar energy exported/injected to the grid.
        grid_demand_kwh: Residual energy imported from the grid.
        self_consumption_rate: Percentage of allocated solar self-consumed.
        solar_coverage_rate: Percentage of demand satisfied by solar self-consumption.
    """

    cups: str
    month: str
    beta: float
    consumption_kwh: float
    generation_allocated_kwh: float
    self_consumed_kwh: float
    surplus_kwh: float
    grid_demand_kwh: float
    self_consumption_rate: float
    solar_coverage_rate: float


@dataclass
class CommunityMonthlyMetrics:
    """Aggregated community-level metrics for a single month.

    Attributes:
        month: Year-month identifier (e.g. '2026-05').
        strategy: Strategy used to compute distribution coefficients.
        total_consumption_kwh: Total consumption across all participating CUPS.
        total_generation_kwh: Total PV generation generated by the solar plant.
        total_self_consumed_kwh: Total solar energy self-consumed collectively.
        total_surplus_kwh: Unused solar generation spilled to the grid.
        total_grid_demand_kwh: Remaining grid demand imported by community members.
        self_consumption_rate: Collective self-consumption efficiency percentage.
        solar_coverage_rate: Collective percentage of energy demand covered by solar.
        beta_sum: Sum of all allocation coefficients (must equal ~1.0).
        cups_metrics: Individual metrics for each participating CUPS.
    """

    month: str
    strategy: str
    total_consumption_kwh: float
    total_generation_kwh: float
    total_self_consumed_kwh: float
    total_surplus_kwh: float
    total_grid_demand_kwh: float
    self_consumption_rate: float
    solar_coverage_rate: float
    beta_sum: float
    cups_metrics: list[CupsMonthlyMetrics] = field(default_factory=list)


@dataclass
class OptimizationResult:
    """Full optimization results across all evaluated months.

    Attributes:
        strategy: The primary allocation strategy applied.
        monthly_results: List of monthly community metrics in chronological order.
        total_summary: Aggregate metrics across the entire evaluated time horizon.
        baselines: Comparison results computed with alternative baseline strategies.
    """

    strategy: str
    monthly_results: list[CommunityMonthlyMetrics]
    total_summary: CommunityMonthlyMetrics
    baselines: dict[str, OptimizationResult] = field(default_factory=dict)
