"""Domain models and data structures for optimization and self-consumption metrics."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum


class OptimizationStrategy(StrEnum):
    """Distribution coefficient allocation strategies."""

    OPTIMAL = "optimal"
    CONSUMPTION_SHARE = "consumption_share"
    EQUAL = "equal"


@dataclass(frozen=True)
class CupsMonthlyMetrics:
    """Monthly self-consumption and energy metrics for an individual CUPS.

    Attributes:
        cups: Universal Supply Point Code identifier.
        month: Year-month identifier (e.g. '2026-05').
        beta: Assigned allocation coefficient (0.0 to 1.0).
        consumption_kwh: Total energy demanded by this supply point in the month.
        generation_allocated_kwh: Share of solar PV generation allocated (beta * total_gen).
        self_consumed_kwh: Solar energy self-consumed on-site (min(consumption, allocated_gen)).
        surplus_kwh: Excess solar energy exported/injected to the grid.
        grid_demand_kwh: Residual energy imported from the grid.
        self_consumption_rate: Percentage of allocated solar self-consumed.
        solar_coverage_rate: Percentage of demand satisfied by solar self-consumption.
    """

    cups: str
    month: str
    beta: float
    consumption_kwh: float
    generation_allocated_kwh: float
    self_consumed_kwh: float
    surplus_kwh: float
    grid_demand_kwh: float
    self_consumption_rate: float
    solar_coverage_rate: float


@dataclass
class CommunityMonthlyMetrics:
    """Aggregated community-level metrics for a single month.

    Attributes:
        month: Month identifier (e.g. '01' to '12' or 'YYYY-MM').
        strategy: Strategy used to compute distribution coefficients.
        total_consumption_kwh: Total consumption across all participating CUPS.
        total_generation_kwh: Total PV generation generated by the solar plant.
        total_self_consumed_kwh: Total solar energy self-consumed collectively.
        total_surplus_kwh: Unused solar generation spilled to the grid.
        total_grid_demand_kwh: Remaining grid demand imported by community members.
        self_consumption_rate: Collective self-consumption efficiency percentage.
        solar_coverage_rate: Collective percentage of energy demand covered by solar.
        beta_sum: Sum of all allocation coefficients (must equal ~1.0).
        cups_metrics: Individual metrics for each participating CUPS.
        has_data: True if the month contains complete data; False if skipped/no-data.
    """

    month: str
    strategy: str
    total_consumption_kwh: float
    total_generation_kwh: float
    total_self_consumed_kwh: float
    total_surplus_kwh: float
    total_grid_demand_kwh: float
    self_consumption_rate: float
    solar_coverage_rate: float
    beta_sum: float
    cups_metrics: list[CupsMonthlyMetrics] = field(default_factory=list)
    has_data: bool = True


@dataclass
class CoefficientsMatrix:
    """Consolidated matrix of distribution coefficients (CUPS in Y, Months in X).

    Attributes:
        cups_list: List of CUPS identifiers (rows).
        months: List of 12 calendar month strings '01'..'12' (columns).
        matrix: Dictionary mapping cups -> {month: beta (0.0 to 1.0) or None}.
        monthly_sums: Dictionary mapping month -> sum of betas (must equal 1.0 or None).
        annual_shares: Dictionary mapping cups -> annual weighted average beta (or None).
        annual_sum: Sum of annual shares (must equal 1.0 or None).
    """

    cups_list: list[str]
    months: list[str]
    matrix: dict[str, dict[str, float | None]]
    monthly_sums: dict[str, float | None]
    annual_shares: dict[str, float | None]
    annual_sum: float | None

    def get_share_pct(self, cups: str, month: str) -> float | None:
        """Get the percentage share for a given CUPS and month, or None if no data."""
        val = self.matrix.get(cups, {}).get(month)
        return (val * 100.0) if val is not None else None

    def format_cell(self, cups: str, month: str, precision: int = 0) -> str:
        """Format share percentage for a given CUPS and month with configured precision, or '—' if no data."""
        val = self.get_share_pct(cups, month)
        if val is None:
            return "—"
        return f"{val:.{precision}f}%"

    def format_annual(self, cups: str, precision: int = 0) -> str:
        """Format annual weighted average share percentage with configured precision, or '—' if no data."""
        val = self.annual_shares.get(cups)
        if val is None:
            return "—"
        return f"{val * 100.0:.{precision}f}%"

    def format_month_sum(self, month: str, precision: int = 0) -> str:
        """Format the total sum of shares for a month with configured precision, or '—' if no data."""
        val = self.monthly_sums.get(month)
        if val is None:
            return "—"
        return f"{val * 100.0:.{precision}f}%"

    def format_annual_sum(self, precision: int = 0) -> str:
        """Format the total sum of annual weighted shares with configured precision, or '—' if no data."""
        if self.annual_sum is None:
            return "—"
        return f"{self.annual_sum * 100.0:.{precision}f}%"


@dataclass
class OptimizationResult:
    """Full optimization results across all evaluated months.

    Attributes:
        strategy: The primary allocation strategy applied.
        monthly_results: List of monthly community metrics in chronological order.
        total_summary: Aggregate metrics across the entire evaluated time horizon.
        baselines: Comparison results computed with alternative baseline strategies.
        cups_list: List of CUPS participating in the community.
    """

    strategy: str
    monthly_results: list[CommunityMonthlyMetrics]
    total_summary: CommunityMonthlyMetrics
    baselines: dict[str, OptimizationResult] = field(default_factory=dict)
    cups_list: list[str] = field(default_factory=list)

    def build_matrix(self) -> CoefficientsMatrix:
        """Construct the 12-month calendar coefficients matrix (January to December)."""
        calendar_months = [f"{m:02d}" for m in range(1, 13)]

        cups_order: list[str] = list(self.cups_list)
        if not cups_order:
            if self.total_summary and self.total_summary.cups_metrics:
                cups_order = [c.cups for c in self.total_summary.cups_metrics]
            elif self.monthly_results:
                for m in self.monthly_results:
                    if m.cups_metrics:
                        cups_order = [c.cups for c in m.cups_metrics]
                        break

        matrix: dict[str, dict[str, float | None]] = {c: {} for c in cups_order}
        monthly_sums: dict[str, float | None] = {}

        # Index monthly results by two-digit month code
        res_by_month: dict[str, CommunityMonthlyMetrics] = {}
        for m in self.monthly_results:
            m_key = m.month[-2:] if len(m.month) >= 2 else f"{int(m.month):02d}"
            res_by_month[m_key] = m

        for m_str in calendar_months:
            m_res = res_by_month.get(m_str)
            if m_res and m_res.has_data and m_res.cups_metrics:
                m_sum = 0.0
                for cm in m_res.cups_metrics:
                    matrix.setdefault(cm.cups, {})[m_str] = cm.beta
                    m_sum += cm.beta
                monthly_sums[m_str] = round(m_sum, 6)
            else:
                for c in cups_order:
                    matrix.setdefault(c, {})[m_str] = None
                monthly_sums[m_str] = None

        # Annual shares: weighted average across complete months with generation
        active_months = [
            m for m in self.monthly_results if m.has_data and m.total_generation_kwh > 0
        ]
        total_gen = sum(m.total_generation_kwh for m in active_months)

        annual_shares: dict[str, float | None] = {}
        if total_gen > 0 and active_months:
            cups_weighted: dict[str, float] = dict.fromkeys(cups_order, 0.0)
            for m in active_months:
                for cm in m.cups_metrics:
                    cups_weighted[cm.cups] += cm.beta * m.total_generation_kwh
            for c in cups_order:
                annual_shares[c] = cups_weighted[c] / total_gen
            annual_sum: float | None = round(
                sum(v for v in annual_shares.values() if v is not None), 6
            )
        elif any(m.has_data for m in self.monthly_results):
            complete_count = sum(1 for m in self.monthly_results if m.has_data)
            for c in cups_order:
                val = sum(
                    matrix[c][m.month[-2:]] or 0.0 for m in self.monthly_results if m.has_data
                )
                annual_shares[c] = val / complete_count
            annual_sum = round(sum(v for v in annual_shares.values() if v is not None), 6)
        else:
            for c in cups_order:
                annual_shares[c] = None
            annual_sum = None

        return CoefficientsMatrix(
            cups_list=cups_order,
            months=calendar_months,
            matrix=matrix,
            monthly_sums=monthly_sums,
            annual_shares=annual_shares,
            annual_sum=annual_sum,
        )
